### ISSUE TITLE
Rightwards movement error when also moving down

### ISSUE THREAD

**Issue by NingWang1729** [NingWang1729/tetris#17]
Rightwards movement sometimes leaves parts of pieces behind when moving down at the same time.

**Comment by NingWang1729** [comment]
Same can happen with leftwards movement.

**Comment by nevinliang** [comment]
react glitching out, or error in algo though? have u tried edge cases (I piece is on the very edge, and you try to rotate it and it doesnt work, so it pauses mid screen).

**Comment by NingWang1729** [comment]
Rotate checks if a piece can be rotated before rotating, so it shouldn't be able to rotate on the edge. It is possible that that could be why pieces get stuck, but it doesn't explain why when they are in the middle and still get stuck.
